//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bill()
        {
            this.prescriptions = new HashSet<prescription>();
            this.clinic_service = new HashSet<clinic_service>();
        }
    
        public int id { get; set; }
        [DisplayName("Id Bệnh Nhân")]
        public int patient_id { get; set; }
        [DisplayName("Ngày tạo")]
        public System.DateTime created_at { get; set; }
        [DisplayName("Nhân Viên Tạo bill")]
        public int staff_created { get; set; }
        [DisplayName("Tổng tiền")]
        public long total_money { get; set; }
        [Browsable(false)]
        public bool is_paid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Browsable(false)]
        public virtual ICollection<prescription> prescriptions { get; set; }
        [Browsable(false)]
        public virtual patient patient { get; set; }
        [Browsable(false)]
        public virtual staff staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Browsable(false)]
        public virtual ICollection<clinic_service> clinic_service { get; set; }
    }
}
