//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medicine()
        {
            this.prescriptions = new HashSet<prescription>();
        }
    
        public int id { get; set; }
        public string medicine_name { get; set; }
        public int quantity_in_sale_unit { get; set; }
        public string sale_unit { get; set; }
        public long sale_price_per_unit { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> expiry_day { get; set; }
        public string entry_unit { get; set; }
        public Nullable<long> entry_price { get; set; }
        public Nullable<System.DateTime> entry_day { get; set; }
        public Nullable<int> unit_exchange_ratio { get; set; }
        public Nullable<int> quantity_in_entry_unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescription> prescriptions { get; set; }
    }
}
