//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medicine()
        {
            this.prescriptions = new HashSet<prescription>();
        }

        public int id { get; set; }
        [DisplayName("Tên Thuốc")]
        public string medicine_name { get; set; }
        [DisplayName("Số lượng /dv Bán")]
        public int quantity_in_sale_unit { get; set; }
        [DisplayName("Đơn Vị Bán")]
        public string sale_unit { get; set; }
        [DisplayName("Giá Bán")]
        public long sale_price_per_unit { get; set; }
        [Browsable(false)]
        public Nullable<bool> is_active { get; set; }
        [DisplayName("Ngày Hết Hạn")]
        public Nullable<System.DateTime> expiry_day { get; set; }
        [DisplayName("Đơn Vị Nhập")]
        public string entry_unit { get; set; }
        [DisplayName("Giá Nhập")]
        public Nullable<long> entry_price { get; set; }
        [DisplayName("Ngày Nhập")]
        public Nullable<System.DateTime> entry_day { get; set; }
        [Browsable(false)]
        public Nullable<int> unit_exchange_ratio { get; set; }
        [DisplayName("Số lượng/dv Nhập")]
        public Nullable<int> quantity_in_entry_unit { get; set; }
        [Browsable(false)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescription> prescriptions { get; set; }
    }
}
