//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescription
    {
        public int bill_id { get; set; }
        public int medicine_id { get; set; }
        public int quantity_indicated { get; set; }
        public string description { get; set; }
        public int staff_id { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual medicine medicine { get; set; }
        public virtual staff staff { get; set; }
    }
}
