//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.accounts = new HashSet<account>();
            this.bills = new HashSet<bill>();
            this.prescriptions = new HashSet<prescription>();
        }
    
        public int id { get; set; }
        [DisplayName("Tên Nhân Viên")]
        public string full_name { get; set; }
        [DisplayName("Ngày Sinh")]
        public System.DateTime date_of_birth { get; set; }
        [DisplayName("Số Điện Thoại")]
        public string phone_number { get; set; }
        [DisplayName("Lương")]
        public long salary { get; set; }
        [Browsable(false)]
        public bool is_still_working { get; set; }
        [Browsable(false)]
        public int permission_id { get; set; }

        [Browsable(false)]
        public virtual permission permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Browsable(false)]
        public virtual ICollection<account> accounts { get; set; }
        [Browsable(false)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Browsable(false)]
        public virtual ICollection<prescription> prescriptions { get; set; }
    }
}
